edition = "2018"
fn_args_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
max_width = 100
merge_derives = true
newline_style = "Native"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

# These following features are still unstable in rustfmt 1.4.6
wrap_comments = true
comment_width = 100
